server:
  port: 8080
logging:
  config: classpath:log/logback-spring.xml
  path: D:/nmyslog/nmys
spring:
  application:
    name: dev
  datasource:
    url: jdbc:mysql://localhost:3306/tale
    username: root
    password: developer
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
