
logging:
  config: classpath:log/logback-spring.xml
  path: D:/nmyslog/nmys
spring:
  application:
    name: dev
  datasource:
    url: jdbc:mysql://localhost:3306/tale
    username: root
    password: developer
    driver-class-name: com.mysql.jdbc.Driver