package com.wechat.joker.tale.pojo;

import java.io.Serializable;

public class Tusers implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.uid
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.username
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.password
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.email
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.home_url
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    private String homeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.screen_name
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    private String screenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.created
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    private Integer created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.activated
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    private Integer activated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.logged
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    private Integer logged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.group_name
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    private String groupName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.uid
     *
     * @return the value of t_users.uid
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.uid
     *
     * @param uid the value for t_users.uid
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.username
     *
     * @return the value of t_users.username
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.username
     *
     * @param username the value for t_users.username
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.password
     *
     * @return the value of t_users.password
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.password
     *
     * @param password the value for t_users.password
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.email
     *
     * @return the value of t_users.email
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.email
     *
     * @param email the value for t_users.email
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.home_url
     *
     * @return the value of t_users.home_url
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public String getHomeUrl() {
        return homeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.home_url
     *
     * @param homeUrl the value for t_users.home_url
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public void setHomeUrl(String homeUrl) {
        this.homeUrl = homeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.screen_name
     *
     * @return the value of t_users.screen_name
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public String getScreenName() {
        return screenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.screen_name
     *
     * @param screenName the value for t_users.screen_name
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.created
     *
     * @return the value of t_users.created
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.created
     *
     * @param created the value for t_users.created
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.activated
     *
     * @return the value of t_users.activated
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public Integer getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.activated
     *
     * @param activated the value for t_users.activated
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public void setActivated(Integer activated) {
        this.activated = activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.logged
     *
     * @return the value of t_users.logged
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public Integer getLogged() {
        return logged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.logged
     *
     * @param logged the value for t_users.logged
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public void setLogged(Integer logged) {
        this.logged = logged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.group_name
     *
     * @return the value of t_users.group_name
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.group_name
     *
     * @param groupName the value for t_users.group_name
     *
     * @mbggenerated Thu Feb 14 15:35:09 CST 2019
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
}